project:
  type: book
  output-dir: docs
  
toc-expand: 2
toc-depth: 5
page-navigation: true
book:
  title: "Git tutorial"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/thomas-rasmussen/git-tutorial
  chapters:
    - index.qmd
    - part: "Part I - The basics"
      chapters: 
        - introduction-to-version-control.qmd
        - introduction-to-git.qmd
        - basic-git.qmd
    - part: "Part II - Branching and remotes"
    - part: "Part III - Stand-alone topics"
      chapters:
        - workflows.qmd
        - github.qmd
        - the-dot-git-folder.qmd
    
  appendices:
    - git-for-windows.qmd
    - graphical-user-interfaces.qmd
    - further-reading.qmd
    - references.qmd

bibliography: references.bib
nocite: |
  @*
  
format:
  html:
    css: styles.css
    theme: minty
    include-in-header:
      text: |
       <script src="custom-js.js"></script>



