project:
  type: book
  output-dir: docs
  preview: 
    browser: true
    watch-inputs: true
    
  
page-navigation: true
book:
  title: "Git tutorial"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/thomas-rasmussen/git-tutorial
  chapters:
    - index.qmd
    - part: "Part I"
      chapters:
      - introduction-to-git.qmd
      - basic-git.qmd
    - part: "Part II"
      chapters:
      - github.qmd
      - the-dot-git-folder.qmd
      
  appendices:
    - git-for-windows.qmd
    - graphical-user-interfaces.qmd
    - further-reading.qmd

format:
  html:
    number-sections: true
    number-depth: 3
    toc: true
    toc-expand: true
    toc-depth: 3
    css: styles.css
    theme: minty
    include-in-header:
      text: |
       <script src="custom-js.js"></script>



