project:
  type: book
  output-dir: docs
  preview: 
    browser: true
    watch-inputs: true
    

page-navigation: true
book:
  title: "Git tutorial"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/thomas-rasmussen/git-tutorial
  chapters:
    - index.qmd
    - part: "Part I"
      chapters:
      - part1-ch01-introduction-to-git.qmd
      - part1-ch02-getting-started.qmd
      - part1-ch03-inspecting-the-commit-history.qmd
      - part1-ch04-undoing-changes.qmd
      - part1-ch05-branching.qmd
      - part1-ch06-merging.qmd
      - part1-ch07-remotes.qmd
      - part1-ch08-workflows.qmd
    - part: "Part II"
      chapters:
      - part2-github.qmd
      - part2-git-internals.qmd
      - part2-git-stash.qmd
      - part2-git-rebase.qmd
      
  appendices:
    - app01-git-for-windows.qmd
    - app02-github-setup.qmd
    - app03-graphical-user-interfaces.qmd
    - app04-configuration-of-git.qmd
    - app05-resources.qmd

format:
  html:
    number-sections: true
    number-depth: 2
    toc: true
    toc-expand: true
    toc-depth: 3
    css: styles.css
    theme: minty
    include-in-header:
      text: |
       <script src="custom-js.js"></script>



