---
title: "Introduction to Git - Notes"
format:
  html:
    toc: true
    self-contained: true
    theme: cosmo
---

# Git for Windows

[Git for Windows](https://gitforwindows.org/){target="_blank"} is a set of tools for Windows users. Of main interest, Git for Windows provides a Bash emulation used to run Git from the command line. Using Git Bash, Windows users can use "git" commands exactly like one would do in Linux and Unix environments. Besides the full set of Git core commands, Git Bash is also packaged with additional shell commands that can be useful.

Here we give a short list of some of the available shell commands in Git Bash, and show with examples how they can be used to create, manipulate, and delete files, which can be useful when using Git.

It is unfortunately not straightforward to get an overview of all available commands and how to use them. The full list of available commands can assessed from files in the `<span style="font-family:monospace">/usr/bin</span>`{=html} directory of the Git Bash installation. Documentation of Linux shell commands in general, and how to use them, can be found with some google-fu. For example, TODO: insert some useful links

## Introduction to Git Bash

When you first open Git Bash, you will see something like this:

```{=html}
<pre style="color:white;background-color:black;padding:0.5em">
<span style="color:green">user_id@computer_id</span> <span style="color:purple">MINGW64</span> <span style="color:yellow">~</span>
$
</pre>
```

TODO: make some css classes to facilitate especially inline Git Bash stuff?
eg git-bash-white/git-bash-yellow etc., or maybe more proper, a git-bash class and then white/yelloe etc color classes? Or maybe that will just make it more words to type and could more easily result in clashes of css definitions?

The "`<span style="font-family:monospace;color:green;background-color:black">user_id@computer_id</span>`{=html}" is an id based on name of the user that is logged in, and the name of the device running Git Bash. The "MINGW64" part in purple is the name of the compiler used to build Git Bash (yes, that is something I googled, and no, I don't know what that means). Both of these things are irrelevant. Of more interest is the "~" in yellow at the end of the first line. 

## Useful Git BASH commands

```{=html}
<table class="table-striped">
  <thead>
    <tr>
      <th style="width:25%">Command</th>
      <th style="width:75%">Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="font-family:monospace">cd</td>
      <td>Change directory</td>
    </tr>
    <tr>
      <td style="font-family:monospace">clear</td>
      <td>Clear terminal window</td>
    </tr>
    <tr>
      <td style="font-family:monospace">echo</td>
      <td>Display a line of text</td>
    </tr>
    <tr>
      <td style="font-family:monospace">ls</td>
      <td>List directory content</td>
    </tr>
    <tr>
      <td style="font-family:monospace">mkdir</td>
      <td>Make directories</td>
    </tr>
    <tr>
      <td style="font-family:monospace">pwd</td>
      <td>Print working dierctory</td>
    </tr>
    <tr>
      <td style="font-family:monospace">rm</td>
      <td>Remove files</td>
    </tr>
    <tr>
      <td style="font-family:monospace">rmdir</td>
      <td>Remove empty directories</td>
    </tr>
    <tr>
      <td style="font-family:monospace">touch</td>
      <td>Change file timestamps</td>
    </tr>
  </tbody>
</table>
```

## Examples



To clear window use clear command. alternatively press {{< kbd Ctrl+l>}}).


In this example we will illustrate how to use the above commands in Git Bash, by creating and manipulating files, and then deleting them again afterwards.

First, we use <span style="font-family:monospace">cd</span> to change the directory to where we want to create a new folder.

```{=html}
<pre style="color:white;background-color:black;padding:0.5em">
<span style="color:green">user_id@computer_id</span> <span style="color:purple">MINGW64</span> <span style="color:yellow">~</span>
$ cd "C:/some/directory"
<span style="color:green">user_id@computer_id</span> <span style="color:purple">MINGW64</span> <span style="color:yellow">/c/some/directory</span>
$
</pre>
```

Git for Windows also comes with shell integration, so alternatively we
can simple navigate to <span style="font-family:monospace">C:/some</span>, right click on the "directory" folder (shift+right click on Windows 11) and
select "Open Git Bash here". The current working directory can be seen 


### First-time Git setup

Describe how to setup Git after installing it. Look to Pro Git for inspiration.

git config stuff that should be done
- Identity : user.name and user.email.
- editor: dont use vim, it is scary. Switch to notepad or notepad++


## More indepth explaination on differnces between SVCS and DVCS's?
## GitHub

Talking about GitHub is probably not something we will touch upon in the presentation / during the seminar, since it is not something that will be used in day to day work. But there should probably
be some information on what it is in the notes.

## Git bash

Write a guide on how to use Git bash for Windows. A list of commands and such would be helpful.
Use material Benjamin has made as inspiration.

## Git internals

Some summarized notes on Git internals from Pro Git maybe. Might be of interest to some people,
but might primarily be of interest to myself / a good place to summarize some stuff that is 
easy to forget but important.

## I fucked up. How do I restore deleted/lost code?

Should for sure be a chapter on this.

## Best practices

Maybe some best practice advice?

- Make incremental small changes

- Only commit code (to master/dev/feature brances) that works as intended

- Write clear concise commit messages.

- Use a consistent branch strategy.


### Central versus distributed VCS's

Will probably not go into details in the presentation, but some extra notes might be
of interest. 

## Resources


https://git-scm.com/docs

Google

Manual pages: git help commands. Refer to these instead of docs on internet. These manpages
are always available offline.

Pro Git book [download](https://git-scm.com/book/en/v2)

https://r-cubed-intro.rostools.org/appendix/extra-github

look into this one: https://learngitbranching.js.org/

This one was pretty fun: https://gitexercises.fracz.com/


## Notes / TODO

### General notes / TODO

- Look into course material from https://r-cubed-intro.rostools.org/appendix/extra-github.
  Their approach is way to cursory compared to what we are going to do here, but it looks
  like som inspiration can be gained from it anyway. In continuation of this, their explaination
  of the motivation to use VCS's instead of manual version control is really good and relatable
  to the audience of this seminar.

### Examples

- Might make sense to include an "examples" folder with subfolders for each exercise
  with all the needed starting files? These could then also be used for examples during
  the presentation? Examples can include files, but not subfolder Git repositories.
  Any example that needs an existing repository could just use this repo? Any other example
  that needs eg a commit history the participants could create themselves. Repeating the
  basic commands many times is probably a good thing anyway.


### notes document


- For each section in the notes, it will probably be a good idea to give some references
  to where the information is comming from.
  
- Consider writing a sectino on git commit message templates as Benjamin has done.
  This could be a useful tool.

### Slides

- Read up on HTML stuff and figure out how to make a custom "terminal code" class that can be
applied to command prompt / git commands that uses a monospace font, uses standard quatation marks
instead of left and right quatation marks etc. Ideally, drop the callout-block approach and make
a custom approach ourselves making a box etc.

- Incorporate a running example illustrating all the introduced concepts and commands? It would probably make
sense to build something reassembling a typical DCE project from scratch? Is a "running exercise" better for this?

- Split up the presentation into 3 separate presentations, once for each part? Might make
  everything a little more manageable? On the other hand it would be nice to have everything together in one file. Maybe only split up if compile times becomes irratingly long and/or file size
  becomes too big (whatever that would be)

- Should there be more info on why/how using Git Bash. Powershell would technically be an alternative. All git commands would work but you would (probably) not be able to do other kinds of basic commands that isnot Git?

- There should be slides/ntoes on how to Setup/configuration of Git
