# Inspecting the commit history

At this point you know how to initialize or clone a Git repository, and record changes to the repository with commits. The obvious question at this point is: how do you see a list of what commits have been made to a Git repository and what changes was made? This is what the `git log` command is for, and what we will talk about in this chapter.

## Data integrity in Git

Before we start talking about the commit histories and changes to files, we need to talk about data integrity and checksums in Git. Any stream of data, for example a file or a directory of files, can be summarized into a single value, a so-called checksum. Even a single bit flip in a data stream would result in an entirely new checksum. Git checksums *everything*. This means that if something changes (including data corruption), Git will know about it. Git uses this to ensure the integrity of a project. In Git everything is checksummed before it is stored, and stored files/directories are referred to by that checksum. It also means that if the checksum of your state of a project (a commit ID) matches the checksum of another clone of the project, you can be assured that the entire project up until that point is identical.

The method that Git uses for making checksums is called a SHA-1 hash. This is a 40-characters string composed of hexadecimal characters and looks something like shown below.

<pre class="terminal">
840552db75d3d52894732b753892427b3f2cafa8
</pre>

Since Git uses checksums so much, you will see these checksums everywhere. In particular, every time you commit a snapshot of files to a Git repository, the snapshot is associated with a checksum value.

## Basic use of `git log`

To illustrate how how to inspect the commit history, we create a simple Git repository to work with.

<pre class="terminal">
$ cd ~
$ mkdir example-git-log
$ cd example-git-log
$ git init
$ echo "First commit" > file.txt
$ git add file.txt
$ git commit -m"First commit"
</pre>

If you use `git log` on this repository, you will get output similar to the below:

<pre class="terminal">
$ git log
<span class="col-hash">commit 3d00987b9c770a8881e1ea1024c119e2c19b091a</span> (HEAD -> main)
Author: Thomas Rasmussen &lt;thomasboejer@gmail.com&gt;
Date:   Mon Oct 13 08:28:10 2025 +0200

    First commit
</pre>

In the output we can see that there have been one commit to the repository, and we are presented with information on the author of the commit, the date of the commit, the commit checksum, and the commit messsage.

Lets add another commit to the repository look at the commit history again:

<pre class="terminal">
$ echo "Second commit" >> file.txt
$ git add file.txt
$ git commit -m"Second commit"
$ git log
commit <span class="col-hash">6ea3956e99f1d0227c01e05622e952bffec0eafc</span> (HEAD -> main)
Author: Thomas Rasmussen &lt;thomasboejer@gmail.com&gt;
Date:   Mon Oct 13 08:33:54 2025 +0200

    Second commit

<span class="col-hash">commit 3d00987b9c770a8881e1ea1024c119e2c19b091a</span>
Author: Thomas Rasmussen &lt;thomasboejer@gmail.com&gt;
Date:   Mon Oct 13 08:28:10 2025 +0200

    First commit
</pre>

We can see that commits are listed in reverse chronological orders, with the newest commit showing up first. We can also see that the information we are shown is quite verbose, and with many commits to a repository will make it hard to get an overview of the commit history. Typically, we are primarily interested in the commit checksum and the commit message of commits to a repository. We can get Git to show us exactly this using the `--oneline` option:

<pre class="terminal">
$ git log --oneline
<span class="col-hash">6ea3956 (</span><span class="col-head">HEAD</span> <span class="col-hash">-></span> <span class="col-branch-local">main</span><span class="col-hash">)</span> Second commit
<span class="col-hash">3d00987</span> First commit
</pre>

Note that when using this option, only the first 7 characters of checksums are shown. Git will automatically show more characters if necessary to make the ID's' unique. At this point you might be concerned about the possibility of different commits having the same checksum, a so-called SHA-1 collision. Don't worry, this is extremely unlikely^[https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection]:

> Here’s an example to give you an idea of what it would take to get a SHA-1
collision. If all 6.5 billion humans on Earth were programming, and every second,
each one was producing code that was the equivalent of the entire Linux kernel
history (6.5 million Git objects) and pushing it into one enormous Git repository, it
would take roughly 2 years until that repository contained enough objects to have
a 50% probability of a single SHA-1 object collision. Thus, an organic SHA-1
collision is less likely than every member of your programming team being
attacked and killed by wolves in unrelated incidents on the same night.

Another thing we are often interested in, is the exact changes that was introduced in a commit. We can tell Git to show us the differences (the patch output) introduced in each commit by applying the `-p` option to `git log`. Let's apply this option together with`--oneline`:

<pre class="terminal">
$ git log --oneline -p
<span class="col-hash">6ea3956</span> (HEAD -> main) Second commit
<span class="col-diff-header">diff --git a/file.text</span> b/file.text
<span class="col-diff-metadata">new file mode 100644</span>
<span class="col-diff-metadata">index 0000000..c133ee6</span>
<span class="col-diff-metadata">--- /dev/null</span>
<span class="col-diff-metadata">+++ b/file.text</span>
<span class="col-diff-hunk-header">@@ -0,0 +1 @@</span>
<span class="col-diff-added">+Second commit</span>
<span class="col-hash">3d00987 First commit</span>
<span class="col-diff-header">diff --git a/file.txt b/file.txt</span>
<span class="col-diff-metadata">new file mode 100644</span>
<span class="col-diff-metadata">index 0000000..6eaf244</span>
<span class="col-diff-metadata">--- /dev/null</span>
<span class="col-diff-metadata">+++ b/file.txt</span>
<span class="col-diff-hunk-header">@@ -0,0 +1 @@</span>
<span class="col-diff-added">+First commit</span>
</pre>

There is a lot of technical information in this output, which we will not discuss, but we can see that the the line of text that was added in each commit is clearly marked in green.

## TODO

Notes:
- Would probably be good to add another file in running example where we remove a line in each commit, so that we can show how removed text is shown with git log -p. 


## Exercises

### Exercise 1



Exercise ideas:
- Construct a simple repository and use git log. Creating the repository ourself makes everything very simple and easy to understand as compared to cloning a real repository.
- Exercise focusing on exploring use of options
- Add exercise where reader has to look at documentation to figure out how to limit the number of log entries that are displayed "-<number>" option.