
# Workflows
   - Might be incorporated into branching and merging chapter?
   - Could also be in Part II
   - Talking about workflows / branching models, how to use Git in projects, branching stratigies etc.
     This is not a tutorial for software developers, so talking about Gitflow,
     trunk-based development and whatever is probably not helpful at all. Probably better     to talk about it in the context of a much simpler setup, eg a single developer
     working on a simple project with a mostly linear history, and small team projects.
     Talk about maybe using a setup with a main/dev branch and feature branches. That
     workflow is very simple and covers pretty much every relevant scenario?
  - Maybe this chapter should be called "Branching models" and the focus should be around that concepet? 
    - Maybe the entire chapter should just be centered around the branching model of using a main branch for "production/releases", dev branch for (working) development version, and feature branches from dev, wehre everything is rebased wehn done so just have a nice simple linear commit history of main branch commits, which are assumed to be the only versions of relevance.
      - Maybe talk about scenarios where this workflow needs to be extended and how to do that. Here it might make sense to mention something like git-flow? How does this setup handle collaboration? People develop in feature branches, that are then merged into dev by a leutanant? This is just feature branch workflow? Maybe look at https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow for inpiration.
